### ISSUE TITLE
package.json almost empty

### ISSUE THREAD

**Issue by nmaxcom** [sensepost/wsproxy#2] opened 2016-12-27 03:59 UTC
Hi guys. You need to fill the dependencies needed otherwise it just keeps complaining of packets that are not installed (because they are not present in the package.json) like:

```

module.js:327
    throw err;
    ^

Error: Cannot find module 'body-parser'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/merl/Desktop/wsproxy/wsprocessor.js:5:18)
    at Module._compile (module.js:409:26)
```

I'm manually inserting express, body-parser, multer, jade...

**Comment by staaldraad** [comment] 2017-01-03 09:04
Hi! Thanks for this. I thought I had fully updated dependencies. Will look into this and fix :+1:

**Comment by pabx06** [comment] 2017-03-23 21:02
npm install express body-parser multer jade --save

**Comment by pabx06** [comment] 2017-03-23 21:12
tryed your proxy on 
`https://www.ig.com/fr/ig-indices/allemagne-30`

keep getting error 

`λ node wsproxy.js
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1028:11)
    at TCP.onread (net.js:572:26)

C:\Users\`

wsproxy exit

**Comment by staaldraad** [comment] 2017-03-30 08:18
hi! sorry for the delay on this. 
I pushed a few small changes that hopefully covers this. I tried against ```https://www.ig.com/fr/ig-indices/allemagne-30``` and can't reproduce the error. 

Are you connecting directly to the wsproxy? My setup is as follows:
Firefox -> burp -> wsproxy

This has a two-fold benefit, you don't have to worry about certificate errors in Firefox, as burp's cert is already trusted. Secondly, you can do the normal testing of web requests you would normally do through Burp.

Hope this helps!

**Comment by staaldraad** [comment] 2017-05-16 18:42
this should all be resolved with https://github.com/sensepost/wsproxy/pull/4

**Closed as completed by staaldraad** 2017-05-16 18:42 UTC
